[package]
name = "weldr-bin"
version = "0.0.1"
authors = ["Jerome Humbert"]
description = "A tool to manipulate LDraw files (.ldr)"
license = "MIT"
repository = "https://github.com/djeedai/weldr"
readme = "README.md"
documentation = "https://docs.rs/weldr-bin"
keywords = ["convert", "ldraw", "lego", "cad"]
categories = ["command-line-utilities", "multimedia::encoding"]
edition = "2018"
include = [
  "CHANGELOG.md",
  "LICENSE",
  "README.md",
  "../../.gitignore",
  "Cargo.toml",
  "src/*.rs",
]

[[bin]]
name = "weldr"
path = "src/weldr.rs"

[dependencies]
weldr = { version = "0.2", path = "../../lib" }
ansi_term = "0.12"
clap = "2.33"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
ordered-float = "2.0"
