name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install gcc-multilib
      run: sudo apt-get install gcc-multilib
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate code coverage
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Lcov
        ls -la
    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: './lcov.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}
