name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.44.0

        features:
          - 'default'
          - ''

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust (${{ matrix.rust }})
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --no-default-features --features "${{ matrix.features }}"

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-default-features --features "${{ matrix.features }}"

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust (stable)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-tarpaulin
      run: |
        RUST_BACKTRACE=1 cargo install --version 0.16.0 cargo-tarpaulin

    - name: Generate code coverage
      run: |
        RUST_BACKTRACE=1 cargo tarpaulin --verbose --workspace --timeout 120 --out Lcov --no-default-features --config tarpaulin.toml
        ls -la

    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: './lcov.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}

  doc:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --features "default"
