name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.44.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust (${{ matrix.rust }})
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Build lib
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path lib/Cargo.toml --verbose

    - name: Build bin/weldr
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path bin/weldr/Cargo.toml --verbose

    - name: Run lib tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path lib/Cargo.toml --verbose

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust (stable)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-tarpaulin
      run: |
        RUST_BACKTRACE=1 cargo install --version 0.16.0 cargo-tarpaulin

    - name: Generate code coverage
      run: |
        RUST_BACKTRACE=1 cargo tarpaulin --verbose --timeout 120 --out Lcov --workspace
        ls -la

    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: 'lcov.info'
        github-token: ${{ secrets.GITHUB_TOKEN }}

  doc:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Doc lib
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --manifest-path lib/Cargo.toml --verbose

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
